name: Playwright Tests

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]

jobs:
  test:
    timeout-minutes: 60
    runs-on: ubuntu-latest

    services:
      backend:
        runs-on: ubuntu-latest
        container:
          image: node:18
        options: --network-alias backend
        ports:
          - 3000:3000
        steps:
          - uses: actions/checkout@v4
          - name: Install backend dependencies
            run: yarn install
            working-directory: backend
          - name: Start backend
            run: yarn dev
            working-directory: backend

    steps:
      - uses: actions/checkout@v4
      
      - uses: actions/setup-node@v4
        with:
          node-version: 18

      - name: Install frontend dependencies
        run: yarn install
        working-directory: frontend

      - name: Start frontend
        run: yarn start
        working-directory: frontend
        env:
          CI: true

      - name: Wait for frontend to be ready
        run: |
          echo "Waiting for frontend to be ready..."
          while ! nc -z localhost 8081; do
            sleep 1
          done

      - name: Install e2e dependencies
        run: yarn install
        working-directory: e2e

      - name: Install Playwright Browsers
        run: npx playwright install --with-deps
        working-directory: e2e

      - name: Run Playwright tests
        run: npx playwright test
        working-directory: e2e

      - uses: actions/upload-artifact@v4
        if: ${{ !cancelled() }}
        with:
          name: playwright-report
          path: e2e/playwright-report/
          retention-days: 30
